### ISSUE TITLE
AuthenticationContext.AcquireTokenAsync using ClientAssertionCertificate is giving error Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by bhushanppatil** [AzureAD/azure-activedirectory-library-for-dotnet#1049]
Hi,
I am using Microsoft.IdentityModel.Clients.ActiveDirectory version 3.19.4 
Trying to generate token from Asp.Net Core API through AuthenticationContext.AcquireTokenAsync using ClientAssertionCertificate 

it is giving following error: 
Object reference not set to an instance of an object
   at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.SignWithCertificate(String message, X509Certificate2 certificate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.JsonWebToken.Sign(IClientAssertionCertificate credential)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientKey.AddToParameters(IDictionary`2 parameters)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBroker>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

not sure whats going wrong it has block me any help will be appreciate 
I am using following code to generate token: 

var myClientId = <aad app clientid>;
ClientAssertionCertificate clientCredentials;
var authenticationContext = new AuthenticationContext(authority);
var certificate = _certificateReader.FindByThumbprint(StoreName.My, StoreLocation.LocalMachine);
using(var x509Store = new X509Store(storeName, storeLocation)){
    x509Store.Open(OpenFlags.ReadOnly);
    var certCollection =
                    x509Store.Certificates.Find(X509FindType.FindByThumbprint, thumbprint);
    clientCredentials = new ClientAssertionCertificate(myClientId, certCollection[0]);
}

var result =
                    await authenticationContext.AcquireTokenAsync(Audience, clientCredentials);

**Comment by bhushanppatil** [comment]
resolved the solution.
My Bad, was using self sign certificate which was not have the valid authority.  Due to this was getting error.

**Comment by jennyf19** [comment]
@bhushanppatil Glad you figured it out, thanks for letting us know and closing the issue.
