### ISSUE TITLE
NullReferenceException on ADAL AquireTokenAsync despite using const variables as paramaters

### ISSUE THREAD

**Issue by lucdem** [AzureAD/azure-activedirectory-library-for-dotnet#1051]
I have the following line of code throwing a NullReferenceException:

`var authResult = await AuthContext.AcquireTokenAsync(Resource, new ClientCredential(Program.ClientId, Program.ClientSecret));`

Resource is a const string, Program.ClientId and Program.ClientSecret are static strings initialized when the program starts and never altered, so I can guarantee with 100% certainty that the parameters aren't null, [and VisualStudio's debugger only confirms it](https://ibb.co/fzvtkd), which makes me think this can't be anything but a bug. 

As you can also see in the picture I linked, I had the program running for over an hour. Access tokens last only 1 hour which means this definitely isn't the first time I get tokens from this exact line of code (in fact getting tokens is one of the first things I do on the program).

I'm using Microsoft.IdentityModel.Clients.ActiveDirectory nuget version 3.19.4. Here's the stacktrace:
```
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__22`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__22`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__72.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__69.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__59.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__33.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__60.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at // rest of the trace is stuff from my code which I believe is irrelevant here
```

**Comment by henrik-me** [comment]
@lucdem we will take a look. I would like to see the entire stack trace and also the logs as that will help the investigation.

**Comment by shahbikash** [comment]
@henrik-me  this the entire exception i have logged in a file. i have tried catching the exception at AdalServiceException and AdalException but its not caught, the exception is caught only in sysytem.exception block.
Please suggest if i am missing something while logging.

**Comment by Yonisha** [comment]
Hi,

any solution for this?

**Comment by jmprieur** [comment]
@Yonisha, do you have a way of enabling logs (as Henrik suggested): to enable them, : https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net
Also do you have repro steps? code that we could run?

**Comment by lucdem** [comment]
Unfortunately (or rather fortunately), after getting this issue twice on the day this post was created I never managed to replicate it again. In fact this exact same piece of code has turned into production code and worked for months now without another occurrence of the issue.

**Comment by jmprieur** [comment]
@lucdem : what should we do then? close this issue?

**Comment by 2troger** [comment]
I just started getting this issue a few days ago as well. I am the only one on my team having this problem. My stacktrace looks identical to the original post's.

I implemented the logging described above, the log goes until the exception is thrown.
After more investigation within my team, this only happens on my computer with certain logins when deployed to iOS and with the production Azure AD. We tested on a prior testing Azure AD and it works.

```
2018-08-23 10:53:59.367 ScannerApp.iOS[49175:1087297] 2018-08-23T15:53:59.3521330Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: ADAL PCL.iOS with assembly version '3.19.8.16603', file version '3.19.8.16603' and informational version '60156f308468ccbe517904f2bb43a8a763434aee' is running...
2018-08-23 10:54:11.410 ScannerApp.iOS[49175:1087297] Information 2018-08-23T15:53:59.3521330Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: ADAL PCL.iOS with assembly version '3.19.8.16603', file version '3.19.8.16603' and informational version '60156f308468ccbe517904f2bb43a8a763434aee' is running...
2018-08-23 10:54:11.411 ScannerApp.iOS[49175:1087297] Information 2018-08-23T15:54:11.4114170Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: ADAL PCL.iOS with assembly version '3.19.8.16603', file version '3.19.8.16603' and informational version '60156f308468ccbe517904f2bb43a8a763434aee' is running...
2018-08-23 10:54:11.414 ScannerApp.iOS[49175:1087297] 2018-08-23T15:54:11.4143570Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.windows.net
2018-08-23 10:54:11.414 ScannerApp.iOS[49175:1087297] Information 2018-08-23T15:54:11.4143570Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.windows.net
2018-08-23 10:54:11.415 ScannerApp.iOS[49175:1087297] Information 2018-08-23T15:54:11.4150070Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: === Token Acquisition started:
	Authority: <Authority>
	Resource: <Resource>
	ClientId: <ClientId>
	CacheType: null
	Authentication Target: User
	
2018-08-23 10:54:11.728 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7286730Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Loading from cache.
2018-08-23 10:54:11.729 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7286730Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Loading from cache.
2018-08-23 10:54:11.729 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7291890Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Loading from cache.
2018-08-23 10:54:11.740 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7400510Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.740 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7400510Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.740 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7404440Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.744 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7444680Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.744 ScannerApp.iOS[49175:1087569] Information 2018-08-23T15:54:11.7444680Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.744 ScannerApp.iOS[49175:1087569] Information 2018-08-23T15:54:11.7447740Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.745 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7449990Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.745 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7449990Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.745 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7452630Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.745 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7454440Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.745 ScannerApp.iOS[49175:1087569] Information 2018-08-23T15:54:11.7454440Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.745 ScannerApp.iOS[49175:1087569] Information 2018-08-23T15:54:11.7457830Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.746 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7459770Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.746 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7459770Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.746 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7463240Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.746 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7465060Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.746 ScannerApp.iOS[49175:1087569] Information 2018-08-23T15:54:11.7465060Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.746 ScannerApp.iOS[49175:1087569] Information 2018-08-23T15:54:11.7468260Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.747 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7470240Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.747 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7470240Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.747 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7473080Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.747 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7475090Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.747 ScannerApp.iOS[49175:1087569] Information 2018-08-23T15:54:11.7475090Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.747 ScannerApp.iOS[49175:1087569] Information 2018-08-23T15:54:11.7478550Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.748 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7480840Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.748 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7480840Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.748 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7484020Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.748 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7486100Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.748 ScannerApp.iOS[49175:1087569] Information 2018-08-23T15:54:11.7486100Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.748 ScannerApp.iOS[49175:1087569] Information 2018-08-23T15:54:11.7488860Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.749 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7491010Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.749 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7491010Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.749 ScannerApp.iOS[49175:1087569] Verbose 2018-08-23T15:54:11.7494210Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Looking up cache for a token...
2018-08-23 10:54:11.749 ScannerApp.iOS[49175:1087569] 2018-08-23T15:54:11.7495880Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.749 ScannerApp.iOS[49175:1087569] Information 2018-08-23T15:54:11.7495880Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:11.750 ScannerApp.iOS[49175:1087569] Information 2018-08-23T15:54:11.7498770Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: No matching token was found in the cache
2018-08-23 10:54:48.826 ScannerApp.iOS[49175:1087363] 2018-08-23T15:54:48.8268280Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Network timeout, Exception type: System.Threading.Tasks.TaskCanceledException
2018-08-23 10:54:48.827 ScannerApp.iOS[49175:1087363] Information 2018-08-23T15:54:48.8268280Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Network timeout, Exception type: System.Threading.Tasks.TaskCanceledException
2018-08-23 10:54:48.827 ScannerApp.iOS[49175:1087363] Information 2018-08-23T15:54:48.8273230Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Network timeout, Exception message: A task was canceled.
2018-08-23 10:54:49.828 ScannerApp.iOS[49175:1088198] 2018-08-23T15:54:49.8279500Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Retrying one more time..
2018-08-23 10:54:49.828 ScannerApp.iOS[49175:1088198] Information 2018-08-23T15:54:49.8279500Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Retrying one more time..
2018-08-23 10:54:49.828 ScannerApp.iOS[49175:1088198] Information 2018-08-23T15:54:49.8287530Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Retrying one more time..
2018-08-23 10:55:19.837 ScannerApp.iOS[49175:1087363] 2018-08-23T15:55:19.8375600Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Network timeout, Exception type: System.Threading.Tasks.TaskCanceledException
2018-08-23 10:55:19.837 ScannerApp.iOS[49175:1087363] Information 2018-08-23T15:55:19.8375600Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Network timeout, Exception type: System.Threading.Tasks.TaskCanceledException
2018-08-23 10:55:19.838 ScannerApp.iOS[49175:1087363] Information 2018-08-23T15:55:19.8379490Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Network timeout, Exception message: A task was canceled.
2018-08-23 10:55:19.838 ScannerApp.iOS[49175:1087363] 2018-08-23T15:55:19.8381590Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Retry Failed, Exception type: System.Threading.Tasks.TaskCanceledException
2018-08-23 10:55:19.838 ScannerApp.iOS[49175:1087363] Information 2018-08-23T15:55:19.8381590Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Retry Failed, Exception type: System.Threading.Tasks.TaskCanceledException
2018-08-23 10:55:19.838 ScannerApp.iOS[49175:1087363] Information 2018-08-23T15:55:19.8384670Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Retry Failed, Exception message: A task was canceled.
2018-08-23 10:55:19.843 ScannerApp.iOS[49175:1087363] 2018-08-23T15:55:19.8431510Z: bd66cb3c-07cb-4f34-8014-70af2b83e54c - LoggerBase.cs: Exception type: System.NullReferenceException
```

**Comment by jmprieur** [comment]
Closing as we cannot repro
