### ISSUE TITLE
AdalServiceException: unknown_error StatusCode: 408

### ISSUE THREAD

**Issue by GitHubSachin** [AzureAD/azure-activedirectory-library-for-dotnet#1113]
Hi,
On few of the production machines we are seeing errors authenticating with AAD, The exception stack trace indicates **AdalServiceException** and **ErrorCode: unknown_error StatusCode: 408**
Is there any way to know when such errors are thrown and what causes them? Unfortunately we don't have correlationid printed in exception stack trace. 

Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: unknown_error: Unknown error ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper.<GetResponseAsync>d__29.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MS.Ess.EsrpClient.Common.Auth.AuthHandler.<AquireToken>d__11.MoveNext() in D:\BuildAgentNonCluster\_work\105\s\src\EsrpClient.Common\Auth\AuthHandler.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MS.Ess.EsrpClient.Common.Auth.AuthHandler.<AcquireTokenAsync>d__10.MoveNext() in D:\BuildAgentNonCluster\_work\105\s\src\EsrpClient.Common\Auth\AuthHandler.cs:line 76
	ErrorCode: unknown_error
	StatusCode: 408<---

**Comment by jmprieur** [comment]
I believe that this is a network issue. See http://www.checkupdown.com/status/E408.html
Did you look at the HttpHeaders member?

**Comment by jmprieur** [comment]
@henrik-me, @trwalke : I don't think that we can do better in term of reporting this kind of issue? or do you think we can?

**Comment by henrik-me** [comment]
@GitHubSachin : you should be able to get the correlation id from other parts of the log. we can't really do much about a 408. ADAL logs which resource it's trying to get a token for including which AAD authority it's accessing. Besides that a 408 is typically a service/web service issue.

Can you pls. clarify "Is there any way to know when such errors are thrown and what causes them?". You already get the exception thus you should know when. Cause, it's a service issue not the client. 

cc: @jmprieur

**Comment by GitHubSachin** [comment]
I dont have the correlation id, but this has not occured in production yet, we deployed a change with logging enabled so hopefully next occurrence if any will have all info to debug.

**Comment by jmprieur** [comment]
Closing this issue as there is no additional information which would enable us to act on it
