### ISSUE TITLE
3.19.8 Linux SignWithCertificate - System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mixxit** [AzureAD/azure-activedirectory-library-for-dotnet#1286]
3.19.8 Linux
Note that to get help, you need to run the latest preview or non-preview version

Docker microsoft/aspnetcore-build:1.0-2.0  .net core2 works fine on Windows

**What authentication flow has the issue?**
* Desktop 
https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential

**Repro**

```csharp
X509Certificate2 cert = ReadCertificateFromStore("CN=TodoListDaemonWithCert");
```

**Expected behavior**
Certificate is read from the local store and an access key returned

**Actual behavior**
```
Error Message:
 System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.)
  ----> System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ADSProcessor.CertAuthentication.GetAccessToken(String todoListResourceId) in /builds/ajw-microservices/ADSProcessor/ADSProcessor/CertAuthentication.cs:line 63
   at ADSProcessor.CertAuthentication.Auth() in /builds/ajw-microservices/ADSProcessor/ADSProcessor/CertAuthentication.cs:line 36
   at ADSProcessorTests.UnitTests.AuthTest() in /builds/ajw-microservices/ADSProcessor/ADSProcessorTests/UnitTests.cs:line 98
--NullReferenceException
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.CryptographyHelper.SignWithCertificate(String message, X509Certificate2 certificate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.ClientCreds.JsonWebToken.Sign(IClientAssertionCertificate credential, Boolean sendX5C)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.ClientCreds.ClientKey.AddToParameters(IDictionary`2 parameters)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ADSProcessor.CertAuthentication.<>c__DisplayClass5_0.<<GetAccessToken>b__0>d.MoveNext() in /builds/ajw-microservices/ADSProcessor/ADSProcessor/CertAuthentication.cs:line 63
```

**Possible Solution**
Run application and unit tests in a windows environment

**Comment by mixxit** [comment]
Unable to run preview due to Windows incompatibility with nuget

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to fetch results from V2 feed at 'http://nuget.prod.aws.ajw-aviation.com/api/v2/FindPackagesById()?id='runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl'&semVerLevel=2.0.0' with following message : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.				
```

**Comment by mixxit** [comment]
Version 4.1.0-preview results:

```
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
Stack Trace:
    at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.SigningHelper.SignWithCertificate(String message, X509Certificate2 certificate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.ClientCreds.JsonWebToken.Sign(IClientAssertionCertificate credential, Boolean sendX5c)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.ClientCreds.ClientKey.AddToParameters(IDictionary`2 parameters)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ADSProcessor.CertAuthentication.<>c__DisplayClass5_0.<<GetAccessToken>b__0>d.MoveNext() in /builds/ajw-microservices/ADSProcessor/ADSProcessor/CertAuthentication.cs:line 63
```

**Comment by jmprieur** [comment]
@mixxit : did you try with this sample: https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-certificate-credential, which is for .NET Core and that I had tested on Linux when I wrote it?

**Comment by mixxit** [comment]
This appears to be an issue with the certificate

**Comment by henrylilei** [comment]
@mixxit We are working on the same scenario and hitting on the same error. Could you please let me know what you did to the cert to make it work on linux? Thanks!
