### ISSUE TITLE
Library crashes on re-entry in WinJS phone app

### ISSUE THREAD

**Issue by mpaliath** [AzureAD/azure-activedirectory-library-for-dotnet#129]
Crashes with the error message 

The text associated with this error code could not be found.

System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler..ctor(Authenticator authenticator, TokenCache tokenCache, IWebAuthenticationBrokerContinuationEventArgs args)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.ContinueAcquireTokenAsync(IWebAuthenticationB

**Comment by daserge** [comment]
Is `Windows.Security.Authentication.Web.WebAuthenticationBroker.getCurrentApplicationCallbackUri()` supported as a `redirectUrl` on Windows Phone 8.1?
I can still see `UriFormatException` in `2.19.208020213`.
