### ISSUE TITLE
AcquireTokenByAuthorizationCodeAsync returns null reference exception when using any type of TokenCache

### ISSUE THREAD

**Issue by kamnyborg** [AzureAD/azure-activedirectory-library-for-dotnet#1429]
Version: ADAL 4.4.1
Platform: net45
Flow: Auth code

Open Id authentication implemented in Identity Server solution.

**Repro**

```csharp
var credential = new ClientCredential(ConfigurationManager.AppSettings["ClientId"],
                ConfigurationManager.AppSettings["AppSecret"]);
            var oid = ctx.AuthenticationTicket.Identity.Claims.LastOrDefault(
                x => x.Type == "http://schemas.microsoft.com/identity/claims/objectidentifier")?.Value;
            var authContext = new AuthenticationContext(ctx.Options.Authority, new TokenCache());
            

            return await authContext.AcquireTokenByAuthorizationCodeAsync(
                 ctx.ProtocolMessage.Code, ctx.Request.Uri, credential, ConfigurationManager.AppSettings["GraphResource"]);
```

When running this code, it fails with the following exception:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

Stack trace:
   at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.StoreToCacheCommon(AdalResultWrapper result, String authority, String resource, String clientId, TokenSubjectType subjectType, RequestContext requestContext)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.<StoreToCacheAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<StoreResultExToCacheAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenByAuthorizationCodeCommonAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenByAuthorizationCodeAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at <**REMOVED**>.IdentityServerConfig.<GetGraphAuthenticationResult>d__7.MoveNext() in <**REMOVED**>\App_Start\IdentityServerConfig.cs:line 231

If I change this line:
```var authContext = new AuthenticationContext(ctx.Options.Authority, new TokenCache());```
with this
```var authContext = new AuthenticationContext(ctx.Options.Authority, null);```
it works, I get a token that I can use for accessing graph (but no token cache is used, which leads to problems further down the road). It seems like any type of token cache makes fetching the auth token fail.

**Additional context/ Logs / Screenshots**
2018-11-26T13:55:53.7611197Z: c238cae6-f007-4c9c-a3f2-be069a483f20 - AdalLoggerBase.cs: ADAL PCL.Desktop with assembly version '4.4.1.0', file version '4.4.1.0' and informational version '4.4.1' is running...

"2018-11-26T13:56:08.5150699Z: c238cae6-f007-4c9c-a3f2-be069a483f20 - AdalLoggerBase.cs: === Token Acquisition started:\n\tAuthority: <**REMOVED**>\n\t<**REMOVED**>\n\tClientId: <**REMOVED**>\n\tCacheType: null\n\tAuthentication Target: User\n\t"

"2018-11-26T13:56:16.3976461Z: c238cae6-f007-4c9c-a3f2-be069a483f20 - AdalLoggerBase.cs: Resource value in the token response was used for storing tokens in the cache"

"2018-11-26T13:56:24.1001863Z: c238cae6-f007-4c9c-a3f2-be069a483f20 - AdalLoggerBase.cs: Storing token in the cache..."

"2018-11-26T13:56:31.2966253Z: c238cae6-f007-4c9c-a3f2-be069a483f20 - AdalLoggerBase.cs: An item was stored in the cache"

"2018-11-26T13:56:37.0787815Z: c238cae6-f007-4c9c-a3f2-be069a483f20 - AdalLoggerBase.cs: System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.StoreToCacheCommon(AdalResultWrapper result, String authority, String resource, String clientId, TokenSubjectType subjectType, RequestContext requestContext)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.<StoreToCacheAsync>d__47.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<StoreResultExToCacheAsync>d__54.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__53.MoveNext()"

**Comment by henrik-me** [comment]
@kamnyborg : Did you try this with any other versions of ADAL?
Currently investigating.

**Comment by kamnyborg** [comment]
@henrik-me: thank you. I have tried with ADAL 4.4.0 and 4.3.0 as well.

**Comment by kamnyborg** [comment]
Just some additional information:

With my own implementation of TokenCache, it goes into OnBeforeAccess with the following TokenCacheNotificationArgs: 
![image](https://user-images.githubusercontent.com/2311623/49064363-f5b2b000-f21a-11e8-94a9-3eee073e870b.png)

Then it goes into OnBeforeWrite with the following TokenCacheNotificationArgs:
![image](https://user-images.githubusercontent.com/2311623/49064297-c8fe9880-f21a-11e8-8280-b0e8747fdc30.png)

**Comment by jmprieur** [comment]
See also MSA's issue [AcquireTokenByAuthorizationCodeAsync should not return a token from the cache if the requested scopes are more than the scopes for the token contained in the cache #693](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/693)

**Comment by kamnyborg** [comment]
I worked this issue out with a colleague: 
Upon registration, my OpenIdConnectAuthenticationOptions Scope was set to "User.Read" via config. This created the issue during AcquireTokenByAuthorizationCodeAsync which cause the null reference exception at one point. When the scopes were set to "openid profile email", it works flawlessly.
