### ISSUE TITLE
Occasional NullReferenceException comming from ADAL Http calls

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/azure-activedirectory-library-for-dotnet#1489]
**Which Version of ADAL are you using ?**
4.5

**Which platform has the issue?**
desktop

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Repro**
1. Perform a standard interactive call. 
2. Ensure the call fails due to a timeout (you can use Fiddler to simulate this)

**Expected behavior**
An AdalServiceException should be thrown

**Actual behavior**
NullReferenceException 

2019-01-24T07:15:54.5446958Z: 7e59e2c4-c704-471b-b685-847c560c0a23 - AdalLoggerBase.cs: Network timeout, Exception message: A task was canceled.
2019-01-24T07:15:55.5599983Z: 7e59e2c4-c704-471b-b685-847c560c0a23 - AdalLoggerBase.cs: Retrying one more time..
2019-01-24T07:16:25.5677407Z: 7e59e2c4-c704-471b-b685-847c560c0a23 - AdalLoggerBase.cs: Network timeout, Exception message: A task was canceled.
2019-01-24T07:16:25.5677407Z: 7e59e2c4-c704-471b-b685-847c560c0a23 - AdalLoggerBase.cs: Retry Failed, Exception message: A task was canceled.
2019-01-24T07:16:25.5677407Z: 7e59e2c4-c704-471b-b685-847c560c0a23 - AdalLoggerBase.cs: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.<GetResponseAsync>d__22`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.InstanceDiscovery.<DiscoverAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.InstanceDiscovery.<GetMetadataEntryAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator.<UpdateFromTemplateAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<PreRunAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__53.MoveNext()
2019-01-24T07:16:55.5728484Z: 4a1d7704-04c3-487a-b67b-725580e299c9 - AdalLoggerBase.cs: Network timeout, Exception message: A task was canceled.
2019-01-24T07:16:56.5795491Z: 4a1d7704-04c3-487a-b67b-725580e299c9 - AdalLoggerBase.cs: Retrying one more time..
2019-01-24T07:17:26.5938823Z: 4a1d7704-04c3-487a-b67b-725580e299c9 - AdalLoggerBase.cs: Network timeout, Exception message: A task was canceled.
2019-01-24T07:17:26.5938823Z: 4a1d7704-04c3-487a-b67b-725580e299c9 - AdalLoggerBase.cs: Retry Failed, Exception message: A task was canceled.
2019-01-24T07:17:26.5938823Z: 4a1d7704-04c3-487a-b67b-725580e299c9 - AdalLoggerBase.cs: System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by jmprieur** [comment]
This is fixed in ADAL 4.5.1 (See #1489)
