### ISSUE TITLE
AADSTS50155: Device is not authenticated

### ISSUE THREAD

**Issue by myokeeh** [AzureAD/azure-activedirectory-library-for-dotnet#1504]
I have a UWP app that has been using ADAL and it's been working up until today. Is this just a authentication service unavailability or something else?

    Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS50155: Device is not authenticated.
    Trace ID: [REMOVED]
    Correlation ID: [REMOVED]
    Timestamp: 2019-02-17 04:40:13Z ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (BadRequest). ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: {"error":"invalid_grant","error_description":"AADSTS50155: Device is not authenticated.\r\nTrace ID: [REMOVED]\r\nCorrelation ID: [REMOVED]\r\nTimestamp: 2019-02-17 04:40:13Z","error_codes":[50155],"timestamp":"2019-02-17 04:40:13Z","trace_id":"178cb0a8-df29-4ebd-bc96-0dc3c0662c00","correlation_id":"[REMOVED]","suberror":"device_authentication_failed"}: Unknown error
       --- End of inner exception stack trace ---
       --- End of inner exception stack trace ---
       at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.GetResponseAsync[T](Boolean respondToDeviceAuthChallenge)
       at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.GetResponseAsync[T]()
       at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.SendHttpMessageAsync(IRequestParameters requestParameters)
       at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.SendTokenRequestAsync()
       at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.CheckAndAcquireTokenUsingBrokerAsync()
       at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
       at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenCommonAsync(String resource, String clientId, Uri redirectUri, IPlatformParameters parameters, UserIdentifier userId, String extraQueryParameters, String claims)
       at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(String resource, String clientId, Uri redirectUri, IPlatformParameters parameters, UserIdentifier userId, String extraQueryParameters)
       at [REMOVED].App.LoginAsync()
    	ErrorCode: invalid_grant
    	StatusCode: 400

**Comment by myokeeh** [comment]
This is not specific to ADAL after all. Got the same thing using MSAL. Pinging Microsoft team member handling password-less sign-in using the Authenticator app.

**Comment by jmprieur** [comment]
@myokeeh 
What probably happens is that the admin of the Azure AD tenant (where this application has been running) has enabled a conditional access policy requiring device authentication (maybe for all apps, maybe for this app, maybe for certain users who are hit).

On Windows 10, the device certificate is held by WAM (Web Account Manager). However ADAL / MSAL don't speak with WAM yet (and we don't expect this to happen in the next 3 months). 

You might want to have a look at the following sample, which uses WAM: https://github.com/azure-samples/active-directory-dotnet-native-uwp-wam

**Comment by myokeeh** [comment]
@jmprieur Hmm. It would have been something I did then. Last thing I did was enable passwordless signin for Azure AD.

**Comment by jmprieur** [comment]
ah yes @myokeeh, that could explain it. I suppose that passwordless is using the device certificate.

Is you machine domain joined or AAD joined? (in which case you could use [Integrated Windows Windows](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-Integrated-authentication-on-Windows-(Kerberos))

**Comment by myokeeh** [comment]
I moved on to using MSAL.
