### ISSUE TITLE
Info Request - Old Bug Behavior

### ISSUE THREAD

**Issue by keystroke** [AzureAD/azure-activedirectory-library-for-dotnet#1629]
Hey folks,

I am working on implementing an ADFS STS instance that will be consumed by Azure PowerShell cmdlets that use ADAL version 2.28.31117.1411 (the latest version available today uses this version of ADAL.NET). Further details of the scenario are not relevant.

I am hitting what looks to be an old bug in this version of ADAL .NET that I can't figure out how to mitigate. Can someone help identify what the issue is / was in this older build? I cannot find looking through the history of the repo or searching online how to mitigate other than updating...

I am hitting this issue:

```
testhost.x86.exe Information: 0 : 07/16/2019 02:04:12:  - TokenCache: Deserialized 65 items to token cache.
testhost.x86.exe Information: 0 : 07/16/2019 02:04:12: d23bd0e7-ef65-4056-961c-9d329e24b38f - TokenCache: Storing token in the cache...
testhost.x86.exe Information: 0 : 07/16/2019 02:04:12: d23bd0e7-ef65-4056-961c-9d329e24b38f - TokenCache: An item was stored in the cache
testhost.x86.exe Error: 0 : 07/16/2019 02:04:12: d23bd0e7-ef65-4056-961c-9d329e24b38f - <RunAsync>d__0: System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformSpecificHelper.CreateSha256Hash(String input)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.LogReturnedToken(AuthenticationResult result)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.PostRunAsync(AuthenticationResult result)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
testhost.x86.exe Information: 0 : 07/16/2019 02:04:12:  - TokenCache: Serializing token cache with 66 items.

```

Seems to be that it is trying to trace a hash of one of the returned values. But what is it trying to hash? Am I omitting a key claim or something in the response? This only occurs using the interactive flow that acquires an authorization code, and then uses the authorization code to retrieve an access token.

Below is an example response from my STS; I tried including a refresh token in the response, as well as setting the "scope" parameter, but this did not make a difference.

```
[07:04:12.22 PM] [IdentitySystemTestHost] [OK] POST https://localhost:50059/adfs/oauth2/token resource=http%3A%2F%2Flocalhost%3A52436%2F&client_id=1950a258-227b-4e31-a9cf-717495945fc2&grant_type=authorization_code&code=d0045b7c-5afe-47c1-86f7-61efe3e05a5d&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob {
  "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjQzOEFFNzhGQkFBRDZGMTNCMjQ1M0FCQkI2RDc3OTk2MkI4NkZGODYiLCJ4NXQiOiJRNHJuajdxdGJ4T3lSVHE3dHRkNWxpdUdfNFkiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiREVMRVRFLU1FLTMxOTMyODUwOSIsImFwcGlkIjoiMTk1MGEyNTgtMjI3Yi00ZTMxLWE5Y2YtNzE3NDk1OTQ1ZmMyIiwidGlkIjoiMDY5MWZkZWYtNTkzMS00NDY2LWFiZjctMmYyMDc2YmQ4NzAwIiwidmVyIjoiMS4wIiwibmJmIjoxNTYzMjQyNjUyLCJleHAiOjE1NjMyNDYyNTIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDU5LzA2OTFmZGVmLTU5MzEtNDQ2Ni1hYmY3LTJmMjA3NmJkODcwMC8iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNDM2LyJ9.oL3po4fX4YXzIeVgH10Ggd9w6GNq7CCX21u2NNfpOe6vILhuVUdVS0XtLAOZyz-C9zyh_O-__j1LYDJJKSJwHbiSYIzuHejkeWDAdXfofPtsxlXGwad3MmBV3FUIXnOKx1TcikSAcBxhDahv--MZwUAZoSdczgO8Lz3eJ4IhK0z42PxLBQXPz3KC3bIsDDIiz9Gn5StT3Q2omfdM1bcBTGu-z3c5NAausE6lP7TbcQHK0dCwPSWaeFNFJYlWDGVnnNV0TbwgEjMiYETKavbIqwwhlNr2RofvkjEq4YtK1O7yz6ANy7QtTe3E6XnvlfKYABvwVa8bi_CwhJhDmmuTsg",
  "id_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjQzOEFFNzhGQkFBRDZGMTNCMjQ1M0FCQkI2RDc3OTk2MkI4NkZGODYiLCJ4NXQiOiJRNHJuajdxdGJ4T3lSVHE3dHRkNWxpdUdfNFkiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiREVMRVRFLU1FLTMxOTMyODUwOSIsInRpZCI6IjA2OTFmZGVmLTU5MzEtNDQ2Ni1hYmY3LTJmMjA3NmJkODcwMCIsInZlciI6IjEuMCIsIm5iZiI6MTU2MzI0MjY1MiwiZXhwIjoxNTYzMjQ2MjUyLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDA1OS8wNjkxZmRlZi01OTMxLTQ0NjYtYWJmNy0yZjIwNzZiZDg3MDAvIiwiYXVkIjoiMTk1MGEyNTgtMjI3Yi00ZTMxLWE5Y2YtNzE3NDk1OTQ1ZmMyIn0.W7F1Ai_eqDEfRngHL52YX3H_d8queqsg-WM3I-PhCbe2CXmUJsEQ4ub1L5lIe-nJIS_bIpzHF9SDYzIE5qRgOSm33dDitKrHkj1n_RAUN8S0DWi8KfNMrDj1AsYdaE9Xw1HCDXACaWdSCbQgJGD_gjZ_A_pmMb8fr8G-Dmqm-SQcxUh2x-yE6K6W7Sc3COsgOBojBgzAeMhijqpJgoGrwj7O7kr6NfH1k0CiHvlNQPKRBDhRfe3BIiNK0k0oOLGoJJjrRyNTiJwTTKvYJoSSfOklQVnB1qgQRFFsfBr8YOOhO9xRTvUt7rDX1niEIC3gXxgYdhr7mNQjfWNVZko48A",
  "refresh_token": null,
  "resource": "http://localhost:52436/",
  "scope": null,
  "token_type": "Bearer",
  "expires_in": 3600,
  "expires_on": 1563246252,
  "not_before": 1563242652
}
```

Below are the claims that I have included in the access and id tokens:

```
[06:40:33.89 PM] AccessToken
[06:40:33.92 PM] name :: DELETE-ME-370140601
[06:40:33.92 PM] oid :: S-1-5-21-3669189023-1629295227-2434348280-1232
[06:40:33.92 PM] sub :: S-1-5-21-3669189023-1629295227-2434348280-1232
[06:40:33.92 PM] email :: DELETE-ME-370140601@localhost
[06:40:33.92 PM] upn :: DELETE-ME-370140601@localhost
[06:40:33.92 PM] unique_name :: DELETE-ME-370140601@localhost
[06:40:33.92 PM] appid :: 15a5b2e0-e56e-4f6e-abf7-110f06fa0cbb
[06:40:33.92 PM] scp :: openid
[06:40:33.92 PM] tid :: 432945b9-259e-46d1-b0d9-35ec6e428470
[06:40:33.92 PM] ver :: 1.0
[06:40:33.92 PM] nbf :: 1563241233
[06:40:33.92 PM] exp :: 1563244833
[06:40:33.92 PM] iss :: https://localhost/432945b9-259e-46d1-b0d9-35ec6e428470/
[06:40:33.92 PM] aud :: test

[06:40:33.92 PM] IdToken
[06:40:33.92 PM] name :: DELETE-ME-370140601
[06:40:33.92 PM] oid :: S-1-5-21-3669189023-1629295227-2434348280-1232
[06:40:33.92 PM] sub :: S-1-5-21-3669189023-1629295227-2434348280-1232
[06:40:33.92 PM] email :: DELETE-ME-370140601@localhost
[06:40:33.92 PM] upn :: DELETE-ME-370140601@localhost
[06:40:33.92 PM] unique_name :: DELETE-ME-370140601@localhost
[06:40:33.92 PM] tid :: 432945b9-259e-46d1-b0d9-35ec6e428470
[06:40:33.92 PM] ver :: 1.0
[06:40:33.92 PM] nbf :: 1563241233
[06:40:33.92 PM] exp :: 1563244833
[06:40:33.92 PM] iss :: https://localhost/432945b9-259e-46d1-b0d9-35ec6e428470/
[06:40:33.92 PM] aud :: 15a5b2e0-e56e-4f6e-abf7-110f06fa0cbb
```

I would greatly appreciate if someone could assist with identifying the underlying issue and how I can work around it; am I omitting something from the response that needs to be present?

Thanks!

**Comment by keystroke** [comment]
Figured it out! I took a deeper look at the claims in my returned tokens, they were missing the oid, email, and sub claims. What I listed above were the claims from a different unit test that traces all the claims. In my actual implementation for the authorization code, I was caching a security token that transformed the names of those claims from their direct values to the longer "schematized" names, and thus they were filtered-out with my filter that omits the excessive Windows claims. Ensuring that all the proper claims are returned in the tokens, I no-longer get the error and am able to complete the scenario E2E.

Thanks! Leave this here for any other internet goers that might encounter same issue (found a lot of SO posts on this error with zero responses...).
