### ISSUE TITLE
user_interaction_required exception

### ISSUE THREAD

**Issue by alexcarreira** [AzureAD/azure-activedirectory-library-for-dotnet#1671]
**Which Version of ADAL are you using ?**
ADAL 5.2.2

**Which platform has the issue?**
 netcore

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of ADAL

**Repro**
We've started to see the user_interaction_required error and after we upgraded to version 5.2.2 the error occurs more than once a day.

```csharp

 TokenCache.DefaultShared.DeserializeAdalV3(Convert.FromBase64String(powerBIToken.Token));

var promptBehaviour = PromptBehavior.Never;

var authenticationResult = Authorize(promptBehaviour).GetAwaiter().GetResult();
```

**Expected behavior**
We expect that the ADAL service was able to refresh the token without user interaction
Steps: 
- 1st login with user interaction
- next logins using the refresh token

**Actual behavior**
Adal service throws an exception.
Exception
user_interaction_required: One of two conditions was encountered: 
1. The PromptBehavior.Never flag was passed, but the constraint could not be honored, because user interaction was required. 
2. An error occurred during a silent web authentication that prevented the http authentication flow from completing in a short enough time frame

**Additional context/ Logs / Screenshots**

```csharp
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: user_interaction_required: One of two conditions was encountered: 1. The PromptBehavior.Never flag was passed, but the constraint could not be honored, because user interaction was required. 2. An error occurred during a silent web authentication that prevented the http authentication flow from completing in a short enough time frame
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.VerifyAuthorizationResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.<PreTokenRequestAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PBIRobots.Agent.Core.Helpers.Security.<>c__DisplayClass11_0.<<Authorize>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at PBIRobots.Agent.Core.Helpers.Security.GetPowerToken(PromptBehavior promptBehaviour)
---> (Inner Exception #0) Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: user_interaction_required: One of two conditions was encountered: 1. The PromptBehavior.Never flag was passed, but the constraint could not be honored, because user interaction was required. 2. An error occurred during a silent web authentication that prevented the http authentication flow from completing in a short enough time frame
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.VerifyAuthorizationResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.<PreTokenRequestAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PBIRobots.Agent.Core.Helpers.Security.<>c__DisplayClass11_0.<<Authorize>b__0>d.MoveNext()
	ErrorCode: user_interaction_required<---
```

**Comment by jennyf19** [comment]
@alexcarreira I assume this was working with earlier versions and just now started failing? Have you tried using a different prompt value, like `Prompt.Auto`? Here's [more info](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-interactively---Public-client-application-flows#properties-or-platformparameters-constructors-parameters-common-to-most-platforms) on the error you are getting. I know there was talk of eSTS not wanting us to use this parameter anymore. Let me know if you are able to use a different prompt value. I don't know enough about your interactive scenario and which acquire token methods you're targeting. Thanks.

**Comment by alexcarreira** [comment]
Hi, I've just edited my description of the issue to be more clarifying. I've added this to the Expected Behaviour

```
"We expect that the ADAL service was able to refresh the token without user interaction
Steps:
1st login with user interaction
next logins using the refresh token"
```
Now, the login works the first time with the user credentials but then when we try to refresh the token using the refresh token without the user interaction the described exception occurs, but just after a day.

**Comment by jennyf19** [comment]
@alexcarreira thanks for the additional information. Can you share the code you are using for the acquire token interactive and silent calls? Which platform?

**Comment by jmprieur** [comment]
@alexcarreira 
Even when there is a refresh token, there are several reasons why interaction can be required. Azure AD, helped by Advanced Thread Protection, for instance, might decide the user need to do 2FA, or other forms of conditional access

Please have a look at https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-handling-exceptions#msaluirequiredexception. This is for MSAL (our recommended library), but the information is similar for ADAL.

cc; @henrik-me

**Comment by jennyf19** [comment]
@alexcarreira any update on this?

**Comment by alexcarreira** [comment]
> @alexcarreira any update on this?

Hello, I  was able to fix the issue by changing the code and use AcquireTokenSilent() from ADAL.
Thank you for your attention

**Comment by jennyf19** [comment]
thanks for the update @alexcarreira
