### ISSUE TITLE
Windows Phone receiving too many authentication_ui_failed: The browser based authentication dialog failed to complete

### ISSUE THREAD

**Issue by maxpert** [AzureAD/azure-activedirectory-library-for-dotnet#265]
We have a Windows Phone app and we are seeing too many crashes from clients saying **Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: authentication_ui_failed: The browser based authentication dialog failed to complete**

Known issue? Here is stack trace for more details:

```
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: authentication_ui_failed: The browser based authentication dialog failed to complete
   at Microsoft.IdentityModel.Clients.ActiveDirectory.WebUI.Authenticate(Uri authorizationUri, Uri redirectUri, IDictionary`2 headersMap, CallState callState)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.AcquireAuthorization()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAndContinueCommon(String resource, String clientId, Uri redirectUri, UserIdentifier userId, String extraQueryParameters, AuthenticationContextDelegate authDelegate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAndContinue(String resource, String clientId, Uri redirectUri, UserIdentifier userId, String extraQueryParameters, AuthenticationContextDelegate authDelegate)
   at ... (our app stack trace below this)
```

**Comment by kpanwar** [comment]
This error is coming from outside of ADAL as authentication is completely outsourced to WAB. ADAL only receives the successful or failed completion of the request.
