### ISSUE TITLE
MissingMethodException "No parameterless constructor defined for this object" when reading from token cache

### ISSUE THREAD

**Issue by tseemann-xematec** [AzureAD/azure-activedirectory-library-for-dotnet#486]
Hi there!

After upgrading Microsoft.IdentityModel.Clients.ActiveDirectory from v3.10 to v3.12, we are experiencing an issue when serializing data to and from our token cache. We are using PCLStorage v1.0.2 for cross-platform access to local files.

After completely deleting the cache file and retrieving a new security token from the Azure AD token provider, data gets saved to the cache with no errors. When reading from the cache afterwards, during a request to AcquireTokenSilently(), we encounter a MissingMethodException when deserializing the data read from the cache file.

Any ideas would be greatly appreciated!

Exception: System.MissingMethodException "No parameterless constructor defined for this object."

Stack Trace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at System.Runtime.Serialization.XmlFormatReaderGenerator.UnsafeGetUninitializedObject(Type type)
   at ReadUserInfoFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadAuthenticationResultFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadAuthenticationResultExFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.ReadObject(Stream stream)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationResultEx.Deserialize(String serializedObject)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.Deserialize(Byte[] state)
   at SeasNve.Runtime.Security.PersistentTokenCache.LoadData()
   at SeasNve.Runtime.Security.PersistentTokenCache..ctor(String fileName)
   at SeasNve.Runtime.Security.TokenAuthenticationProvider..ctor(String authority, String resource, String clientId, String redirectUrl, Func`1 platformParametersProvider)

**Comment by kpanwar** [comment]
Looks like a different package is being used for JSON (de)serialization and it may be causing issues. What was the version of Serialization package before?

**Comment by tseemann-xematec** [comment]
Serialization is done via System.Runtime.Serialization according to the call stack, so no additional serialization packages are used. In addition, the local cache file has been deleted to ensure that no older cache is causing any version mismatch.

We are experiencing the following flow:
1. Run app from scratch with no existing cache file
2. Call AcquireTokenAsync causing a logon request via the Azure AD logon page
3. The token is received and cached in a newly created local cache file
4. Requests using the token are completed successfully as expected
5. Restart app
6. Call AcquireTokenSilentAsync causing ADAL to acquire the token from the cache
7. Data is read from the cache file and deserialized using the inherited TokenCache.Deserialize(), resulting in the MissingMethodException

**Comment by agent354** [comment]
@tseemann-xematec Did you find any solution for this?  I'm experiencing the same issue.

**Comment by tseemann-xematec** [comment]
No, we are still struggling with it. We have a suspicion that the problem may be related to the fact that our company has added an ADFS token provider to our on-prem AD, so users are being authenticated by ADFS instead of Azure AD. It seems odd though, as the problem did not exist before 3.12 and our ADFS was added some time before that. What is your setup? Are you using ADFS as well?

**Comment by agent354** [comment]
I'm using straight up connection to Azure AD.  Was originally trying to integrate into my application but it was failing so I tried the sample at https://github.com/Azure-Samples/active-directory-webapp-webapi-multitenant-openidconnect-aspnetcore and even that fails with no changes.  Are you able to use as a earlier release because I haven't been able to find one that works.

**Comment by tseemann-xematec** [comment]
In our situation the problem started when we upgraded from 3.10 to 3.12, so I would assume that 3.10 still works. I will try to downgrade some time during next week to see if my assumption is correct. Are you using PCLStorage to persist the cache as well, or are you using something else?

**Comment by kpanwar** [comment]
Adal uses .net built-in serialization API and no dependency on pcl storage.

**Comment by tseemann-xematec** [comment]
I am aware of that. I thought maybe the cache file itself, which in our case is handled by PCLStorage, was somehow being corrupted. Do you have any suggestions where to look for the cause of this problem? What class in the token cache stream could be missing a default constructor?

**Comment by kpanwar** [comment]
I am sorry but I cannot repro this issue on my end. I created a sample desktop app where I referenced 3.10 and acquired a token and I serialized the cache to the disk. I created another desktop app refrencing 3.12 where I simply reloaded the persisted cache and checked the cache size.

**Comment by kpanwar** [comment]
@agent354 - are you using some other library to persist the data?

**Comment by agent354** [comment]
@kpanwar Did you try repro the issue with sample aspnetcore web application mentioned above?  I'm guessing it might have to do with that framework also?  I had tried using Session and Entity framework to store the data.  I was able to rollback to 3.10 and get it working.

**Comment by martincalsyn** [comment]
I am seeing this as well in a UWP app using 3.12 installed from nuget.  The simplest repro is:

                var cleartext = this.Serialize();
                this.Deserialize(cleartext);

I get the 'no parameterless constructor' during deserialization in AuthenticationResultEx.cs

**Comment by kpanwar** [comment]
This is interesting because with 3.12 we started using netcore GA packages. The code for AuthenticationResultEx, AuthenticationResult and UserInfo classes have not changed for a while!

**Comment by kpanwar** [comment]
@martincalsyn, @agent354, @tseemann-xematec  This issue in UWP is happening because of Microsoft.NetCore.UniversalWindowsPlatform > 5.0.0. Cache deserialization works just fine with 5.0.0. Can  you all please confirm what version of netcore platform is being used at your end?

**Comment by tseemann-xematec** [comment]
Affirmative. We are using Microsoft.NetCore.UniversalWindowsPlatform v5.2.1.

**Comment by kpanwar** [comment]
Looks the CoreFx is the right place for this issue. https://github.com/dotnet/corefx/issues/10374

**Comment by tseemann-xematec** [comment]
@kpanwar I understand from the dotnet/corefx roadmap that this issue will not be fixed until milestone 1.1, which is scheduled for release November 30 '16. We have tried to downgrade the Microsoft.NetCore.UniversalWindowsPlatform package from 5.2.1 to 5.1.0 as a temporary workaround. Unfortunately we are now facing a version conflict on System.Net.Sockets. When building our UWP project (part of a Xamarin Forms solutions) after the downgrade to 5.1.0, we are now getting the following error:

Payload contains two or more files with the same destination path 'System.Net.Sockets.dll'. Source files: 
...\packages\runtime.win.System.Net.Sockets\4.1.0\runtimes\win\lib\netcore50\System.Net.Sockets.dll
...\packages\System.Net.Sockets\4.0.0\lib\netcore50\System.Net.Sockets.dll			

Any ideas?

**Comment by tseemann-xematec** [comment]
Hi again! The "Payload contains two or more files with the same destination path" error above was a result of using ADAL 3.12 together with Microsoft.NetCore.UniversalWindowsPlatform 5.1.0. We have now also downgraded ADAL to 3.10 and thereby eliminated this error.

We are really looking forward to having the dotnet/corefx issue fixed, so that we are not forced to stay on an old version of ADAL.

**Comment by kpanwar** [comment]
you can try to add
    "System.Runtime.Serialization.Json": "4.0.1",
    "System.Runtime.Serialization.Primitives": "4.1.0",
    "System.Runtime.Serialization.Xml": "4.1.0",
    "System.Private.DataContractSerialization": "4.1.0"

in your project.json and still be able to use 3.13.0

**Comment by tseemann-xematec** [comment]
I tried adding those packages but keep getting these two errors:

Payload contains two or more files with the same destination path 'System.Net.Sockets.dll'. Source files: 
C:\Users\tse\.nuget\packages\runtime.win.System.Net.Sockets\4.1.0\runtimes\win\lib\netcore50\System.Net.Sockets.dll
C:\Users\tse\.nuget\packages\System.Net.Sockets\4.0.0\lib\netcore50\System.Net.Sockets.dll

Payload contains two or more files with the same destination path 'System.Threading.Timer.dll'. Source files: 
C:\Users\tse\.nuget\packages\runtime.any.System.Threading.Timer\4.0.1\lib\netcore50\System.Threading.Timer.dll
C:\Users\tse\.nuget\packages\System.Threading.Timer\4.0.0\lib\netcore50\System.Threading.Timer.dll

The project.json file now looks like this:
{
  "dependencies": {
    ...
    "Microsoft.Bcl": "1.1.10",
    "Microsoft.Bcl.Build": "1.0.21",
    "Microsoft.IdentityModel.Clients.ActiveDirectory": "3.13.1",
    "Microsoft.Net.Http": "2.2.29",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "System.Private.DataContractSerialization": "4.1.0",
    "System.Runtime.Serialization.Json": "4.0.1",
    "System.Runtime.Serialization.Primitives": "4.1.0",
    "System.Runtime.Serialization.Xml": "4.1.0",
    "Xamarin.Forms": "2.3.0.107",
    ...
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}

**Comment by kpanwar** [comment]
You can use Microsoft.NETCore.UniversalWindowsPlatform 5.2.2 and override specific packages like I suggested. That should clean up the error hopefully. If it does not then you can clear out the packages folder so that there is nothing in first place to complain about. :)

**Comment by tseemann-xematec** [comment]
Ah, I see. So by forcing the project to use older versions of System.Runtime.Serialization.* and System.Private.DataContractSerialization, we can still use the new Microsoft.NETCore.UniversalWindowsPlatform and ADAL packages.

I just tried this and got rid of the compiler errors :) Hopefully, this doesn't cause any runtime issues because of incompatibility between these older packages and NETCore 5.2.2 ;-)

Thanks very much for your help!

**Comment by glatzert** [comment]
I stumbled over this bug, by trying to use the session as a TokenCache in a Asp.NET Core application(because we need a Farm aware Token cache there).

Would it be feasible to just add an empty constructor, so the Serialization will work again or configure the Deserializer to know which constructor to call?

**Comment by kpanwar** [comment]
Adding default constructor did not actually resolve the problem. It means there is also some other data type inside the class that does not support default constructor.
