### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object in v2.28.2

### ISSUE THREAD

**Issue by yavuzozge** [AzureAD/azure-activedirectory-library-for-dotnet#568]
I observe the following exception in ADAL v2.28.2 running on Win 10 phones.

11/21/2016 02:23:24: a03b8aa0-1688-49cf-939b-93646869d293 - AcquireTokenHandlerBase.cs: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpHelper.<SendPostRequestAndDeserializeJsonResponseAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestByRefreshTokenAsync>d__d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RefreshAccessTokenAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()

**Comment by weharc** [comment]
+1 I have the same issue. Annoyingly we only see it in one environment, the dev environment works fine. Authenticating against ADFS 3.0, this exception is thrown after the user enters valid credentials when prompted by the ADFS form. We've traced the network traffic and compared between the environments and can't sport any obvious differences.

**Comment by kpanwar** [comment]
Can you share complete logs for this issue?

**Comment by jmprieur** [comment]
@kpanwar please update this issue

**Comment by jmprieur** [comment]
Closing the issue as we did not receive the logs
