### ISSUE TITLE
Add System.Runtime.Serialization.Primitives as NuGet dependency

### ISSUE THREAD

**Issue by tomkerkhove** [AzureAD/azure-activedirectory-library-for-dotnet#643]
When pulling in the `Microsoft.IdentityModel.Clients.ActiveDirectory` NuGet package it doesn't have `System.Runtime.Serialization.Primitives` as a dependency.

Unfortunately when you run it it starts complaining about the lack of that dependency:
```'Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator' threw an exception.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator.<UpdateFromTemplateAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<PreRunAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()```

Would it be possible to bring this package in as a dependency?

**Comment by kpanwar** [comment]
Which platform are you targeting? I clearly see System.Runtime.Serialization.Primitives referenced in the nuget dependency https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory

**Comment by tomkerkhove** [comment]
.NET Framework 4.6.1 for which there are no dependencies, as far as I can see

**Comment by kpanwar** [comment]
@tomkerkhove - 4.6.1 should not require a nuget reference. It should all be resolved by the .NET framework installed on the machine.

**Comment by tomkerkhove** [comment]
@kpanwar It didn't and I presume it did not for @sujesharukil as well. For what it's worth, it was in VS2015 but it's been a while.
