### ISSUE TITLE
Destination array was not long enough when using Service Principal

### ISSUE THREAD

**Issue by anqzha** [AzureAD/azure-activedirectory-library-for-dotnet#653]
Hi Team,

I am from Azure Data Factory team and need your help about using service principal. 

Our customers provide their application id/key and tenant to make our service available to access their ADLS account. Most customers’ scenario work well but some encounter strange error message. We guess it is because of invalid id/key/tenant provided by customer, but actually all of such situation can report meaningful error message within our tries. So, I cannot repo this issue. Maybe you have seen this error and have more knowledge when such error is thrown and how to resolve it.

My purpose is to avoid such error or provide meaningful error message to the customer in our service after the root cause is known. Thanks for your help!

**Our Code Snippet**
string authString = string.Format(@"https://login.windows.net/{0}", tenant);
AuthenticationContext authenticationContext = new AuthenticationContext(authString);
ClientCredential clientCredential = new ClientCredential(applicationId, applicationKey);
AuthenticationResult authenticationResult = authenticationContext.AcquireToken("https://datalake.azure.net/", clientCredential);

**Call Stack**
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Array.CopyTo(Array array, Int32 index)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.EncodingHelper.UrlEncode(Char[] message)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.EncodingHelper.AddStringWithUrlEncoding(StringBuilder messageBuilder, String key, Char[] value)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.RequestParameters.AddSecureParametersToMessageBuilder(StringBuilder messageBuilder)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.RequestParameters.ToStringBuilder()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.RequestParameters.WriteToStream(Stream stream)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpHelper.<SendPostRequestAndDeserializeJsonResponseAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__1a.MoveNext()

Regards,
Anqing

**Comment by kpanwar** [comment]
what is the library version? If you are not on the latest then please update.

**Comment by anqzha** [comment]
Thank you, Kpanwar. Our library version is 2.19.0.0. So you mean this is a known issue and has been fixed in higher version? The latest version is 2.28.4, right?

**Comment by kpanwar** [comment]
Yes.

**Comment by kpanwar** [comment]
This is in change logs along with the actual fix made in the code.

**Comment by anqzha** [comment]
Hi, kpanwar. I double checked the ADAL version used in our service. It is 2.28.0.725, not 2.19.0.0. Sorry for the wrong info provided before. So, is it true this issue was fixed between 2.28.0 and 2.28.4? **Could you please provide the link of related change log?** Thanks.

I need this details to avoid taking the upgrade effort, but issue remains.
