### ISSUE TITLE
Retry acquiring token in case of certain network issues

### ISSUE THREAD

**Issue by bganapa** [AzureAD/azure-activedirectory-library-for-dotnet#695]
we sporadically run in to AadAuthenticationFailedException while acquiring token for various sporadic network issues. The following is one such kind, ADAL should retry acquiring the token on these kind of time outs by default. if not by default, it should expose a flag for retries

Microsoft.Azure.Commands.Common.Authentication.AadAuthenticationFailedException: user_realm_discovery_failed: User realm discovery failed: The operation has timed out ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: user_realm_discovery_failed: User realm discovery failed ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.UserRealmDiscoveryResponse.<CreateByDiscoveryAsync>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.DoAcquireToken(AdalConfiguration config, PromptBehavior promptBehavior, String userId, SecureString password) in D:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Authentication\UserTokenProvider.cs:line 267
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.SafeAquireToken(AdalConfiguration config, ShowDialog showDialog, String userId, SecureString password, Exception& ex) in D:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Authentication\UserTokenProvider.cs:line 183

**Comment by jmprieur** [comment]
This seems reasonable to provide a way for developers to set a timeout programmatically, but the current timeout seems to be 30s, which is already a lot. 
Let's investigate if we are doing the right thing.

**Comment by kpanwar** [comment]
@bganapa - What ADAL are you using? In v3, ADAL does an automatic retry after 1 second for http requests that failed with network timeouts or HTTP 500-599.

**Comment by bganapa** [comment]
We have been using 2.28* version through azure powershell. I will check with azure powershell team whether we could move over 3* version @markcowl

**Comment by rishavraj10** [comment]
Hi, I am noticing the similar error intermittently. We are using 2.14 version of ADAL library. Are the internal retries not in place in this version. Were they added only in v3? 
@kpanwar can you help?

**Comment by jmprieur** [comment]
@rishavraj10 : I've already replied in https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1502
