### ISSUE TITLE
Request invalid or malformed while trying to get a accesstoken

### ISSUE THREAD

**Issue by saurabh500** [AzureAD/azure-activedirectory-library-for-dotnet#699]
I am using samples\AdalDesktopTestApp to retrieve the access token for a STS url with a client ID using Integrated authentication.

While using the code, I get an error 
```
Federated service at https://msft.sts.microsoft.com/adfs/services/trust/13/windowstransport returned error: ID3035: The request was not valid or is malformed.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.WsTrustRequest.<SendRequestAsync>d__3.MoveNext() in D:\netcore\azure-activedirectory-library-for-dotnet\src\ADAL.PCL\Flows\NonInteractive\WsTrustRequest.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenNonInteractiveHandler.<PreTokenRequest>d__5.MoveNext() in D:\netcore\azure-activedirectory-library-for-dotnet\src\ADAL.PCL\Flows\NonInteractive\AcquireTokenNonInteractiveHandler.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext() in D:\netcore\azure-activedirectory-library-for-dotnet\src\ADAL.PCL\Flows\AcquireTokenHandlerBase.cs:line 198
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__52.MoveNext() in D:\netcore\azure-activedirectory-library-for-dotnet\src\ADAL.PCL\AuthenticationContext.cs:line 575
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.<AcquireTokenAsync>d__0.MoveNext() in D:\netcore\azure-activedirectory-library-for-dotnet\src\ADAL.Common\AuthenticationContextIntegratedAuthExtensions.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AdalDesktopTestApp.Program.<AcquireTokenAsync>d__1.MoveNext() in D:\netcore\azure-activedirectory-library-for-dotnet\samples\AdalDesktopTestApp\Program.cs:line 59

```

The code looks something like this 

```
string resource = "https://database.windows.net/";
            AuthenticationContext context = new AuthenticationContext("https://login.windows.net/72F988BF-86F1-41AF-91AB-2D7CD011DB47", true);
            var result = await context.AcquireTokenAsync(resource,
                "CLIENT_ID".ToUpper(),
                new UserCredential());
            
            string token = result.AccessToken;
            Console.WriteLine(token + "\n");
```

To rule out whether its a Integrated Auth issue, I also tried user and password to login and it didn't work either. I end up with the same exception message as above.

To test if my inputs are correct, I tried to get an access token using Java SDK for ADAL and I could successfully retrieve an access token using the username and password. 

While using username and password auth the error message has a different URL as expected, but the error message and code are the same
```
Federated service at https://msft.sts.microsoft.com/adfs/services/trust/13/usernamemixed returned error: ID3035: The request was not valid or is malformed.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.WsTrustRequest.<SendRequestAsync>d__3.MoveNext() in D:\netcore\azure-activedirectory-library-for-dotnet\src\ADAL.PCL\Flows\NonInteractive\WsTrustRequest.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenNonInteractiveHandler.<PreTokenRequest>d__5.MoveNext() in D:\netcore\azure-activedirectory-library-for-dotnet\src\ADAL.PCL\Flows\NonInteractive\AcquireTokenNonInteractiveHandler.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext() in D:\netcore\azure-activedirectory-library-for-dotnet\src\ADAL.PCL\Flows\AcquireTokenHandlerBase.cs:line 198
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__52.MoveNext() in D:\netcore\azure-activedirectory-library-for-dotnet\src\ADAL.PCL\AuthenticationContext.cs:line 575
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.<AcquireTokenAsync>d__0.MoveNext() in D:\netcore\azure-activedirectory-library-for-dotnet\src\ADAL.Common\AuthenticationContextIntegratedAuthExtensions.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AdalDesktopTestApp.Program.<AcquireTokenAsync>d__1.MoveNext() in D:\netcore\azure-activedirectory-library-for-dotnet\samples\AdalDesktopTestApp\Program.cs:line 59
```

How do I get past this issue?

**Comment by saurabh500** [comment]
I figured out that the rstTrustNameSpace at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/fcefaf606979f67d56ded73dcbaf558b499c454a/src/ADAL.PCL/Flows/NonInteractive/WsTrustRequest.cs#L143 has a trailing "/" causing the failure while retrieving the token from Azure AD. 

I validated using Curl that with the "/" for TrustNameSpace, the server returns an error and without the "/" the response is returned. 

However when I made the change, one of the tests starts failing, because it expects a trailing "/" in the schema name. The Test is` WsTrustRequestXmlFormatTest` which tries to validate the WSTrustRequest payload against the schema. It seems like the client is doing the right thing, but the service is throwing an exception. 
Any insights into, what is the right thing to do here?

**Comment by duncanpMS** [comment]
Thanks for raising this issue @saurabh500. As a workaround, can you use version 3.13.9 of the library instead? We fixed some formatting errors in v3.14 to make the client schema-compliant, so the older version of the library should work.

**Comment by HSAR** [comment]
I've confirmed a repro of the bug using the test code above. It doesn't occur in 3.13.9, and we will be fixing it in 3.14.1 (to be released shortly).

**Comment by HSAR** [comment]
Thanks for reporting the issue!

**Comment by HSAR** [comment]
We've released [3.14.1](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/v3.14.1) to fix this. Thanks for reporting!

**Comment by saurabh500** [comment]
Thanks for the fix.
