### ISSUE TITLE
AcquireToken occationally throws System.Runtime.Serialization.SerializationException

### ISSUE THREAD

**Issue by tehcrashxor** [AzureAD/azure-activedirectory-library-for-dotnet#720]
Occasionally, we have a batch of our `AcquireTokenAsync(string resource, IClientAssertionCertificate clientCertificate)` calls fail with a `System.Runtime.Serialization.SerializationException` like:
```
System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type Microsoft.IdentityModel.Clients.ActiveDirectory.TokenResponse. Encountered unexpected character '<'. ---> System.Xml.XmlException: Encountered unexpected character '<'.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, XmlException exception)
   at System.Runtime.Serialization.Json.XmlJsonReader.Read()
   at System.Xml.XmlBaseReader.IsStartElement()
   at System.Xml.XmlBaseReader.IsStartElement(XmlDictionaryString localName, XmlDictionaryString namespaceUri)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalIsStartObject(XmlReaderDelegator reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.EncodingHelper.DeserializeResponse[T](String response)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

No convenient Correlation or Trace IDs in the exceptions.

**Comment by kpanwar** [comment]
logs statements should contain the correlation id. please share those for us to look any further.

**Comment by benleonard101** [comment]
I have been getting this on every call? Was this ever resolved?

**Comment by jmprieur** [comment]
Do you have repro steps, @benleonard101 ?

**Comment by webster354** [comment]
@benleonard101 I had the same problem with this exception being thrown every single time. 

The solution for me was to fix the the authority URL. Based on the sample code from Microsoft's [https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/blob/1fbde7c25316274a4abaab64893957a80269e1e5/TaskWebApp/App_Start/Startup.Auth.cs#L142](active-directory-b2c-dotnet-webapp-and-webapi) the authority URL is built using the tenant and default policy. The authority URL that I was using was returning a HTTP 404 error because I was not using the correct tenant and policy.

**Comment by MatSFT** [comment]
@oishi-code what was the fix you applied? I am getting the same exception but the code you are pointing to has been updated to something else now

**Comment by not-not-kevin** [comment]
@MattSFT If I remember correctly, the issue I had was with my configuration and there was a typo in the URL being built from the AppSettings values.

Try checking whether the `MetadataAddress` is valid.
https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/blob/1373293341761e09975060c9799b6818fc6f1f51/TaskWebApp/App_Start/Startup.Auth.cs#L38
