### ISSUE TITLE
Obtaining the Retry-After header from ADAL on 429 Too Many Requests errors

### ISSUE THREAD

**Issue by tehcrashxor** [AzureAD/azure-activedirectory-library-for-dotnet#721]
In our discussions with AAD STS and Graph teams following last week's throttling of the VSTS and the entire MS tenant, we've been asked to use the value of the `Retry-After` headers they send on 429: Too Many Request errors to know how long to we should wait before a retry. However, ADAL is currently not providing that (nor any other header value) onto the `AdalServiceException`s.

I don't see one, but is there any way we can get those values today?  If not, any thoughts on adding this functionality?

Additionally, we found that we received three different error traces.  Examples:

1)

    Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Too Many Requests ---> System.Net.Http.HttpRequestException:  Response status code does not indicate success: 429 (429). ---> System.Exception: Too Many Requests
       --- End of inner exception stack trace ---
       at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper.<GetResponseAsync>d__29.MoveNext()
       --- End of inner exception stack trace ---
       at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__20`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---

2)

    Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS90055: The server has terminated the request due to excessive request rate. Please wait a few seconds and try again.
    Trace ID: b0f35b59-7342-406f-9379-00a2e3de2400
    Correlation ID: 7c8e8729-ab77-4638-afa9-394d550e774c
    Timestamp: 2017-07-10 20:43:00Z ---> System.Net.Http.HttpRequestException:  Response status code does not indicate success: 429 (429). ---> System.Exception: {"error":"invalid_request","error_description":"AADSTS90055: The server has terminated the request due to excessive request rate. Please wait a few seconds and try again.\r\nTrace ID: b0f35b59-7342-406f-9379-00a2e3de2400\r\nCorrelation ID: 7c8e8729-ab77-4638-afa9-394d550e774c\r\nTimestamp: 2017-07-10 20:43:00Z","error_codes":[90055],"timestamp":"2017-07-10 20:43:00Z","trace_id":"b0f35b59-7342-406f-9379-00a2e3de2400","correlation_id":"7c8e8729-ab77-4638-afa9-394d550e774c"}
       --- End of inner exception stack trace ---
       at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper.<GetResponseAsync>d__29.MoveNext()
       --- End of inner exception stack trace ---
       at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__20`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---

3)

     Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS90055: The server has terminated the request due to excessive request rate. Please wait a few seconds and try again.
    Trace ID: 6c1eab00-68a7-4b52-b0b5-87e6ba7b2700
    Correlation ID: 7e3663f5-a77d-42c0-bb64-87ee97974209
    Timestamp: 2017-07-10 20:28:29Z ---> System.Net.Http.HttpRequestException:  Response status code does not indicate success: 429 (429). ---> System.Exception: {"error":"invalid_request","error_description":"AADSTS90055: The server has terminated the request due to excessive request rate. Please wait a few seconds and try again.\r\nTrace ID: 6c1eab00-68a7-4b52-b0b5-87e6ba7b2700\r\nCorrelation ID: 7e3663f5-a77d-42c0-bb64-87ee97974209\r\nTimestamp: 2017-07-10 20:28:29Z","error_codes":[90055],"timestamp":"2017-07-10 20:28:29Z","trace_id":"6c1eab00-68a7-4b52-b0b5-87e6ba7b2700","correlation_id":"7e3663f5-a77d-42c0-bb64-87ee97974209"}
       --- End of inner exception stack trace ---
       at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper.<GetResponseAsync>d__29.MoveNext()
       --- End of inner exception stack trace ---
       at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__20`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---

Any reason for the different versions here?  Or should we just ignore that, and treat them all alike?

**Comment by jmprieur** [comment]
@tehcrashxor : I've added it to our backlog.

**Comment by trwalke** [comment]
I have added a property to AdalServiceException called Headers that will contain all of the headers returned when an exception is thrown. It is a collection of type HttpResponseHeaders.

please install the latest version.
Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory -Version 3.17.0-alpha24201 -Source https://www.myget.org/F/aad-clients-nightly/api/v3/index.json

**Comment by kpanwar** [comment]
i have validated the fix.
