### ISSUE TITLE
UWP App AccquireTokenAsync(resource, clientCredential) throws exception on second run

### ISSUE THREAD

**Issue by KJee85** [AzureAD/azure-activedirectory-library-for-dotnet#727]
This is easy to reproduce:

Visual Studio 2017 => New UWP App
References:
Microsoft.IdentityModel.Clients.ActiveDirectory (3.14.2)
Microsoft.NETCore.UniversalWindowsPlatform (5.3.3)

In MainPage() I put standard code to get token via client secret:

```
var authority = "https://login.microsoftonline.com/myTenant";
var authContext = new AuthenticationContext(authority);
ClientCredential credential = new ClientCredential(myClientId, myClientSecret);
var result = authContext.AcquireTokenAsync(myResource, credential).GetAwaiter().GetResult();
```

When you run the app for the first time this works fine, you get a result and it has the token as expected. Running the app a second time results in this exception:

```
System.ArgumentNullException occurred
  HResult=0x80004003
  Message=Value cannot be null.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.StubHelpers.HStringMarshaler.ConvertToNativeReference(String managed, HSTRING_HEADER* hstringHeader)
   at Windows.Security.Cryptography.CryptographicBuffer.ConvertStringToBinary(String value, BinaryStringEncoding encoding)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.CreateSha256Hash(String input)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.LogReturnedToken(AuthenticationResult result)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.PostRunAsync(AuthenticationResult result)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__49.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__26.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AdalTester.MainPage..ctor() in c:\blah\AdalTester\AdalTester\MainPage.xaml.cs:line 32
   at AdalTester.AdalTester_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_MainPage() in c:\blah\AdalTester\AdalTester\obj\x86\Debug\XamlTypeInfo.g.cs:line 178
   at AdalTester.AdalTester_XamlTypeInfo.XamlUserType.ActivateInstance() in c:\blah\AdalTester\AdalTester\obj\x86\Debug\XamlTypeInfo.g.cs:line 334
```

How can I have the client secret flow work in a UWP app. The actual app I need this to work in is a Kiosk type scenario so a user cannot log in, it needs to be able to do this silently.

**Comment by HSAR** [comment]
Hi @KJee85, thanks for reporting this issue. I've reproduced the issue and I'm working on a fix to go out in a future release.

**Comment by kpanwar** [comment]
@KJee85 - You should not be using confidential client flows in uwp app. this would allow anyone to grab a network trace and steal your client secret.

**Comment by KJee85** [comment]
@kpanwar This is a Kiosk type scenario, this app runs on locked down machines in a controlled environment running on Assigned Access mode in windows 10. What other flow would you suggest I use. We are looking at moving to certs in the long term but couldn't because of this exact same issue so now that is fixed maybe we can at least move to that.

**Comment by kpanwar** [comment]
@KJee85 - Does your Kiosk scenario have a user in the play? It would be helpful to understand your scenario usage fully.

**Comment by KJee85** [comment]
Well yes there are obviously users of the app, most of the features though do no require any user identity, and its function is something that needs to just be on and available not waiting for someone to have to sign in.

These users however, given the assigned access mode would be unable to grab anything let alone a network trace to steal the client secret.

**Comment by kpanwar** [comment]
What is the app attempting to do by using confidential client tokens?

**Comment by KJee85** [comment]
The app is a wrapper for a secured website, users hitting this in browser, or in our desktop app on their devices login as expected with their credentials via the websites ADAL.js. 

The Kiosk though is not a user device, its something that multiple users would use over a given day, because of this it needs to just login silently using its own build of the app that does this client secret flow. It is then secured physically and in OS via Assigned Access.
