### ISSUE TITLE
Using a certificate with non-exportable private key with AcquireTokenAsync(string resource, IClientAssertionCertificate clientCertificate) on dotNet 4.7

### ISSUE THREAD

**Issue by EranBE** [AzureAD/azure-activedirectory-library-for-dotnet#752]
Related to this issue - [https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/708](url)

If you target .Net 4.7 and try to use a certificate client assertion with a certificate that has a non-exportable private key, a `CryptographicException` will be thrown since the current code calls `certificate.PrivateKey.ToXmlString(true)` which cannot export the private key.
Prior to .Net 4.7 the same certificate worked since it returned `RSACryptoServiceProvider` as its private key instance.

**Comment by dmcweeney** [comment]
Hi,

We are having same problem here. Upgraded projects to target .Net Framework 47. Also did a pile of package updates - mainly upgrading from asp.net core 1.2 to 2.0.

On my machine code runs fine but on other dev machines we are getting the same error:

System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.
at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
at System.Security.Cryptography.Utils._ExportKey(SafeKeyHandle hKey, Int32 blobType, Object cspObject)
at System.Security.Cryptography.RSACryptoServiceProvider.ExportParameters(Boolean includePrivateParameters)
at System.Security.Cryptography.RSA.ToXmlString(Boolean includePrivateParameters)
at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.GetCryptoProviderForSha256(X509Certificate2 certificate)
at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.SignWithCertificate(String message, X509Certificate2 certificate)
at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate.Sign(String message)
at Microsoft.IdentityModel.Clients.ActiveDirectory.JsonWebToken.Sign(IClientAssertionCertificate credential)
at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientKey.AddToParameters(IDictionary`2 parameters)
at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext()

Any idea of an ETA?

Thanks

Donal

**Comment by stevechhu** [comment]
Hi,

I am also trying to upgrade my app to .net core 2.0 target 4.7, and encountered this issue... 
I made my cert exportable when i was importing it in local machine and got it to work on local but the problem is when you deploy the same app to Azure, there is no way to make the cert exportable...

System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.
at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
at System.Security.Cryptography.Utils._ExportKey(SafeKeyHandle hKey, Int32 blobType, Object cspObject)
at System.Security.Cryptography.RSACryptoServiceProvider.ExportParameters(Boolean includePrivateParameters)
at System.Security.Cryptography.RSA.ToXmlString(Boolean includePrivateParameters)
at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.GetCryptoProviderForSha256(X509Certificate2 certificate)
at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.SignWithCertificate(String message, X509Certificate2 certificate)
at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate.Sign(String message)
at Microsoft.IdentityModel.Clients.ActiveDirectory.JsonWebToken.Sign(IClientAssertionCertificate credential)
at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientKey.AddToParameters(IDictionary`2 parameters)
at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__64.MoveNext()

Thanks,
Steve

**Comment by kpanwar** [comment]
@EranBE @stevechhu - We have a nightly DEV package out with the fix. Please try it out and let us know if it worked for you too. We will be cutting an official release following the feedback. 
Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory -Version 3.16.1-alpha24505 -Source https://www.myget.org/F/aad-clients-nightly/api/v3/index.json

**Comment by stevechhu** [comment]
@kpanwar  I tried locally and in deployed Azure WebApp, both are working with the 3.16.1-alpha24505 version upgrade and targeting net 4.7.

**Comment by dmcweeney** [comment]
I had to revert back to net fx 4.61... so cannot test this... Sorry

**Comment by EranBE** [comment]
@kpanwar I also managed to test our code with the provided private build while targeting .Net 4.7.
Works both for our local deployment and azure deployment.

**Comment by kpanwar** [comment]
Official package has been released https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/3.16.1.
